### PR TITLE
Added a preference to hide status bar icon

### PR DESCRIPTION
**Pull request by stigger**

### CODE REVIEW

**Comment by rurza** [comment]
The code looks great (I'm at work now and can't build it now) but I have a question. When the user has hidden status bar icon, how this can be undone?

**Comment by stigger** [comment]
If the app is running, then the second attempt to launch it will show the preferences (see https://github.com/rurza/NepTunes/pull/9/files#diff-b6bfd93c94b496678bedcb198ad03efbR59)

**Comment by rurza** [comment]
sure I'm going to add this funcionality, but lately I made a lot of changes to the architecture of the app (I wrote first version when I was learning programming). I'm going to re-imlement your changes. Do you mind?

**Comment by stigger** [comment]
No, of course not.

**Pull request closed without merging**
